# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # - board: planck_rev6
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
  # - board: glove80_lh
  # - board: glove80_rh

  # My eyelash boards running BLE without a dongle and using BLE status advertisements
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
  - board: eyelash_corne_left
    shield: settings_reset
  - board: eyelash_corne_right
    shield: nice_view

  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_corne_central_dongle_oled
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_left nice_view_custom
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_right nice_view_custom    
    
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_PM_SOFT_OFF=y
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_PM_SOFT_OFF=y
  - board: seeeduino_xiao_ble
    shield: settings_reset